#!/bin/sh
# SPDX-FileCopyrightText: 2026 Munsik-Park
# SPDX-License-Identifier: Elastic-2.0
# =============================================================================
# /autoflow:install — CLAUDE.local.md identity scaffold (deterministic seam)
# Issue #943 — marketplace-cache-based root-layer stamp
# =============================================================================
# Writes a derived AutoFlow identity draft to $TARGET_ROOT/CLAUDE.local.md, but
# ONLY when that file is absent. If it already exists, exit 0 without writing
# (R3 — never overwrite a target-authored file). Prints which branch it took.
#
# Env contract (feature-design §3.3):
#   TARGET_ROOT      consuming project root (default ${CLAUDE_PROJECT_DIR:-$PWD})
#   ORG REPO DEFAULT_BRANCH TOPOLOGY   derived by detect.sh (display values)
#
# Empty derived fields render as an explicit "(set manually)" placeholder so the
# user sees exactly what to fill rather than a silently dropped line.
# =============================================================================

set -u

TARGET_ROOT="${TARGET_ROOT:-${CLAUDE_PROJECT_DIR:-$PWD}}"
ORG="${ORG:-}"
REPO="${REPO:-}"
DEFAULT_BRANCH="${DEFAULT_BRANCH:-}"
TOPOLOGY="${TOPOLOGY:-}"

DEST="$TARGET_ROOT/CLAUDE.local.md"

# R3: never overwrite a pre-existing target-authored file.
if [ -e "$DEST" ]; then
  printf 'CLAUDE.local.md present at %s -- skipped (R3: never overwrite a target-authored file)\n' "$DEST"
  exit 0
fi

# Render a value, or the "(set manually)" placeholder when it is empty.
val() {
  if [ -n "$1" ]; then
    printf '%s' "$1"
  else
    printf '(set manually)'
  fi
}

case "$TOPOLOGY" in
  single) TOPO_LABEL="single-repo" ;;
  multi)  TOPO_LABEL="multi-repo" ;;
  *)      TOPO_LABEL="(set manually)" ;;
esac

mkdir -p "$(dirname "$DEST")"
cat > "$DEST" <<EOF
# CLAUDE.local.md — Local Overrides

<!-- AutoFlow identity record (draft — generated by /autoflow:install from git state; edit freely) -->
## AutoFlow identity
- Org: $(val "$ORG")
- Repo: $(val "$REPO")
- Default branch: $(val "$DEFAULT_BRANCH")
- Topology: $TOPO_LABEL

<!-- add personal preferences / local URLs / temporary overrides below -->
EOF

printf 'wrote derived CLAUDE.local.md draft to %s (edit/confirm the identity fields before committing)\n' "$DEST"
exit 0
